export const ROLES = {
    ADMIN: "ADMIN",
    SUBADMIN: "SUBADMIN",
    USER: "USER",
    MANUFACTURER: "MANUFACTURER/IMPORTER",
    DISTRIBUTOR: "DISTRIBUTOR",
    DEALER: "DEALER",
    APPROVERS: "APPROVERS"
}